apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-svc
spec:
  type: LoadBalancer
  selector:
    app: reverseproxy
  ports:
    - port: 8080          # external port
      targetPort: 80      # container port
      protocol: TCP
