version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Dockerhub login
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build images
          command: |
            # Reverse proxy
            docker build \
              -t "$DOCKERHUB_USERNAME"/reverseproxy:latest \
              ./reverseproxy

            # User service
            docker build \
              -t "$DOCKERHUB_USERNAME"/udagram-api-user:latest \
              ./udagram-api-user

            # Feed service
            docker build \
              -t "$DOCKERHUB_USERNAME"/udagram-api-feed:latest \
              ./udagram-api-feed

            # Frontend
            docker build \
              -t "$DOCKERHUB_USERNAME"/udagram-frontend:latest \
              ./udagram-frontend

      - run:
          name: Push images
          command: |
            docker push "$DOCKERHUB_USERNAME"/udagram-reverseproxy:latest
            docker push "$DOCKERHUB_USERNAME"/udagram-api-user:latest
            docker push "$DOCKERHUB_USERNAME"/udagram-api-feed:latest
            docker push "$DOCKERHUB_USERNAME"/udagram-frontend:latest

workflows:
  version: 2
  build_and_push_on_commit:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - main
